*

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!apps/gate
!libs/theme

!apps/*/package.json
!libs/*/package.json
!plugins/*/ui/package.json

**/node_modules
apps/gate/web/themes/light/styles.css
apps/gate/Dockerfile*

**/.env
**/.env.*
