*

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml

!plugins
!libs
!.docker/hub-with-plugins/plugins-builder.sh

!apps/*/package.json

**/node_modules
**/.svelte-kit
**/build
plugins/*/ui/dist

**/.env
**/.env.*
